// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaPWZyRWy4ziT-9zT2gm4TwC2EjQNtisk',
    appId: '1:456450312762:web:7fcadbc7979eb6bcbd4303',
    messagingSenderId: '456450312762',
    projectId: 'zoove-8872a',
    authDomain: 'zoove-8872a.firebaseapp.com',
    storageBucket: 'zoove-8872a.appspot.com',
    measurementId: 'G-C27PS22TCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNbXrZbKeA9tYb4BQ5vuCdmDrwJPMxv4',
    appId: '1:456450312762:android:49680d87136f448abd4303',
    messagingSenderId: '456450312762',
    projectId: 'zoove-8872a',
    storageBucket: 'zoove-8872a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUVVcntT2Tz-LNmButltcoFW75xT6no4s',
    appId: '1:456450312762:ios:573923ca31b76fbabd4303',
    messagingSenderId: '456450312762',
    projectId: 'zoove-8872a',
    storageBucket: 'zoove-8872a.appspot.com',
    iosBundleId: 'com.example.zooventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUVVcntT2Tz-LNmButltcoFW75xT6no4s',
    appId: '1:456450312762:ios:719113210576f7eebd4303',
    messagingSenderId: '456450312762',
    projectId: 'zoove-8872a',
    storageBucket: 'zoove-8872a.appspot.com',
    iosBundleId: 'com.example.zooventure.RunnerTests',
  );
}
